### ISSUE TITLE
Modular approach to signing

### ISSUE THREAD

**Issue by mirceanis** [walleth/kethereum#17]
Currently the only signing method exposed is:
`fun signMessage(message: ByteArray, keyPair: ECKeyPair): SignatureData`
which hashes the message using `keccak` and then signs the hash using the given keyPair. The signature is then canonicalized.
This method is suitable for ETH signing but that's about it.

A given set of keys can be used to sign other types of signatures and it makes sense to me to allow customization of the hashing method and canonicalization.

I propose exposing an extra signing method to allow other signing algorithms to be used.

**Comment by ligi** [comment]
I agree - thanks for the thought.

**Comment by mirceanis** [comment]
Great
I've got some ideas and will get back with a proposal PR.
I'd like to assign myself to this but don't have enough rights.

**Comment by ligi** [comment]
great - thought you should have the right to assign issues to yourself as a member of this org

**Comment by mirceanis** [comment]
Thought so too, but apparently I don't

**Comment by ligi** [comment]
can you try again - might have found the problem

**Comment by mirceanis** [comment]
@ligi Thanks for merging
Would it be possible to make a new release with this included?

**Comment by ligi** [comment]
sure thing - it is 0.37
