### ISSUE TITLE
Kotlin SHA2 / SHA256 Implementation

### ISSUE THREAD

**Issue by ligi** [walleth/kethereum#34]
Or find a pure Kotlin implementation - work towards #1

Helpful resources:

 * https://rosettacode.org/wiki/SHA-256
 * https://en.wikipedia.org/wiki/SHA-256
 * http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf

**Comment by atoulme** [comment]
Would you be interested in https://github.com/consensys/cava and particularly https://consensys.github.io/cava/docs/java/latest/ ?

**Comment by ligi** [comment]
yes
