### ISSUE TITLE
Prefixed signature support

### ISSUE THREAD

**Issue by generalpiston** [walleth/kethereum#48]
`eth_sign`: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign. Signatures derived from `eth_sign` should take on this form: `sign(keccak256("\x19Ethereum Signed Message:\n" + len(message) + message)))`. Seems like something wallet providers should handle.

**Comment by ligi** [comment]
can you elaborate a bit more what you propose?

**Comment by ligi** [comment]
closing this for now - please reopen with a more clear description what you have in mind here

**Comment by generalpiston** [comment]
I had to add it myself in https://github.com/sigillabs/mobidex/blob/3dcd0783c5743268d795a3d8e6f069ad0c229c7e/android/app/src/main/java/io/mobidex/WalletManagerModule.java#L397.

There are two ways that would work:
1. Add the message to https://github.com/walleth/kethereum/blob/master/crypto/src/main/kotlin/org/kethereum/crypto/Sign.kt#L30 ?
2. Add a new method `ECKeyPair` called `signMessageWithPrefix`?

Idea 2 seems to make the most sense to maintain backwards compatibility.

**Comment by generalpiston** [comment]
Perfect! Thank you!
