### ISSUE TITLE
high-throughput ABI & RLP (enhancement)

### ISSUE THREAD

**Issue by esaulpaugh** [walleth/kethereum#56]
ABI: full signature parsing. has tunable fuzz test.

RLP: supports types including floating point, chars, booleans, negative integers. has (parsable) json-like RLP object notation. on-demand iterator-based decoding interface

Apache 2.0

https://github.com/esaulpaugh/headlong

**Comment by ligi** [comment]
Thanks for the link - but I am not sure what the action item for KEthereum here is - can you ealborate?

**Comment by esaulpaugh** [comment]
My project recently became available in maven central and it seemed to fit with the general concept of KEthereum, so I was thinking it might be useful if it was added as a dependency so that its API would be available to end-users of KEthereum and/or that it could be later integrated into existing KEthereum functionality. If not, any feedback about it would still be very useful for me.

**Comment by ligi** [comment]
Thanks - I will have a look at the project. But I really do not want to add it as a dependency as it would be a regression regarding #1 - so I am closing this issue now
