### ISSUE TITLE
ERC-681

### ISSUE THREAD

**Issue by ligi** [walleth/kethereum#7]
At DevCon3 we finally have consensus on ERC-681 (https://github.com/ethereum/EIPs/pull/681#issuecomment-341837330) - so now we need implementations of it - at least 2 to get this thing merged. Also do not forget to ping @nagydani after implementing so he can do the interoperability test (plan so far MyEtherWallet<>WALLETH) which is the condition to get this EIP merged.

**Comment by miohtama** [comment]
@issueth My bot friend, how does the bounty address work? The message is not self explanatory.

**Comment by ligi** [comment]
@miohtama here you find some information: http://walleth.org/2017/10/18/issuETH-ethereum-issue-bounties/
